name: gitlab

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    #if: "!(contains(github.event.head_commit.message, 'nogl'))"

    steps:
    - uses: actions/checkout@v2

    - name: Git setup
      run: |
          sudo git config --global user.name ${{secrets.UNAME}}
          sudo git config --global user.email ${{secrets.EMAIL}}
          sudo git clone https://${{secrets.UNAME}}:${{secrets.GH_TOKEN}}@github.com/mpadge/pkgreport
          sudo git fetch --unshallow origin
          sudo git remote add gitlab https://${{secrets.UNAME}}:${{secrets.GLPW}}@gitlab.com/mpadge/pkgreport.git
          sudo git push --force gitlab master
